name: Release

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Select the repository to publish to'
        required: true
        type: choice
        options:
          - Releases
          - Snapshots

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Debug secrets
        run: |
          echo "Username length: ${#DEFTU_PUBLISHING_USERNAME}"
          echo "Password length: ${#DEFTU_PUBLISHING_PASSWORD}"
        env:
          DEFTU_PUBLISHING_USERNAME: ${{ secrets.DEFTU_PUBLISHING_USERNAME }}
          DEFTU_PUBLISHING_PASSWORD: ${{ secrets.DEFTU_PUBLISHING_PASSWORD }}


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run publish task
        env:
          DEFTU_PUBLISHING_USERNAME: ${{ secrets.DEFTU_PUBLISHING_USERNAME }}
          DEFTU_PUBLISHING_PASSWORD: ${{ secrets.DEFTU_PUBLISHING_PASSWORD }}
        run: ./gradlew publishAllPublicationsToDeftu${{ github.event.inputs.repository }}Repository -Pdeftu.publishing.username=${{ secrets.DEFTU_PUBLISHING_USERNAME }} -Pdeftu.publishing.password=${{ secrets.DEFTU_PUBLISHING_PASSWORD }}
